import io
import json
import os
import subprocess
import time
from pathlib import Path

import httpx
import numpy as np
import onnxruntime as ort
import requests
from PIL import Image as PILImage
from tokenizers import Tokenizer

from ai.models import ModerationLog
from reports.models import Report

_BASE = Path(__file__).resolve().parent
_MODEL_DIR = _BASE / "models"
_ONNX_PATH = str(_MODEL_DIR / "model-int8.onnx")
_TOKENIZER_PATH = str(_MODEL_DIR / "tokenizer" / "tokenizer.json")
_LABELS_PATH = _MODEL_DIR / "labels.json"
_VIOLENCE_ONNX = str(_MODEL_DIR / "violence-int8.onnx")
_VIOLENCE_LABELS = _MODEL_DIR / "violence-labels.json"
_DEEPFAKE_ONNX = str(_MODEL_DIR / "deepfake-int8.onnx")
_DEEPFAKE_LABELS = _MODEL_DIR / "deepfake-labels.json"
_DEEPFAKE_PROC = str(_MODEL_DIR / "deepfake-processor.json")

_NSFW_MODEL = "Falconsai/nsfw_image_detection"
_LABEL_MAP = {"NO": "non-offensive", "OO": "offensive", "OR": "racist", "OS": "sexist"}
_VIDEO_TIMESTAMPS = [0, 5, 10, 15, 20]

_AI_EXIF_MARKERS = [
    "midjourney", "dall.e", "dalle", "stable diffusion",
    "stable diffusion webui", "ai generated", "generated by",
    "adobe firefly", "firefly", "createai", "openai",
    "stability.ai", "dreamstudio", "leonardo.ai",
]

_text_session = None
_tokenizer = None
_labels = None
_violence_session = None
_violence_labels = None
_deepfake_session = None
_deepfake_labels = None
_deepfake_proc = None


def _ensure_vision_models():
    global _violence_session, _violence_labels, _deepfake_session, _deepfake_labels, _deepfake_proc
    if _violence_session is not None:
        return
    _violence_session = ort.InferenceSession(_VIOLENCE_ONNX)
    with open(_VIOLENCE_LABELS) as f:
        _violence_labels = json.load(f)
    _deepfake_session = ort.InferenceSession(_DEEPFAKE_ONNX)
    with open(_DEEPFAKE_LABELS) as f:
        _deepfake_labels = json.load(f)
    with open(_DEEPFAKE_PROC) as f:
        _deepfake_proc = json.load(f)


def _ensure_text_model():
    global _text_session, _tokenizer, _labels
    if _text_session is not None:
        return
    _text_session = ort.InferenceSession(_ONNX_PATH)
    _tokenizer = Tokenizer.from_file(_TOKENIZER_PATH)
    _tokenizer.enable_padding(pad_id=0, pad_token="[PAD]", length=128)
    _tokenizer.enable_truncation(max_length=128)
    with open(_LABELS_PATH) as f:
        _labels = json.load(f)


def _hf_post(model: str, image_bytes: bytes, content_type: str) -> list:
    token = os.getenv("HF_TOKEN")
    resp = httpx.post(
        f"https://router.huggingface.co/hf-inference/models/{model}",
        headers={"Authorization": f"Bearer {token}", "Content-Type": content_type},
        content=image_bytes,
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()


def _hf_post_text(model: str, text: str) -> list:
    token = os.getenv("HF_TOKEN")
    resp = httpx.post(
        f"https://router.huggingface.co/hf-inference/models/{model}",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json={"inputs": text},
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()


def _has_devanagari(text: str) -> bool:
    return any(0x0900 <= ord(c) <= 0x097F for c in text)


def _extract_frame(url: str, timestamp: float) -> bytes:
    try:
        subprocess.run(["ffmpeg", "-version"], capture_output=True, timeout=5)
    except FileNotFoundError:
        return None
    cmd = [
        "ffmpeg",
        "-ss", str(timestamp),
        "-i", url,
        "-vframes", "1",
        "-f", "image2pipe",
        "-vcodec", "png",
        "-",
    ]
    proc = subprocess.run(cmd, capture_output=True, timeout=60)
    if proc.returncode != 0:
        return None
    return proc.stdout


def moderate_report(report: Report) -> str:
    token = os.getenv("HF_TOKEN")
    if not token:
        _apply_decision(report, Report.AIStatus.APPROVED, ["AI moderation disabled (no HF token)"])
        return Report.AIStatus.APPROVED

    _ensure_vision_models()

    all_reasons = []
    start = time.time()

    txt = f"{report.title} {report.description}"

    if _has_devanagari(txt):
        _ensure_text_model()
        try:
            _moderate_text_onnx(txt, all_reasons)
        except Exception as e:
            all_reasons.append(f"Local text moderation error: {str(e)}")

    try:
        _moderate_text_multilingual(txt, all_reasons)
    except Exception as e:
        all_reasons.append(f"API text moderation error: {str(e)}")

    try:
        _moderate_images(report, all_reasons)
    except Exception as e:
        all_reasons.append(f"Image moderation error: {str(e)}")

    try:
        _moderate_videos(report, all_reasons)
    except Exception as e:
        all_reasons.append(f"Video moderation error: {str(e)}")

    elapsed = time.time() - start
    ai_status = Report.AIStatus.FLAGGED if all_reasons else Report.AIStatus.APPROVED

    _apply_decision(report, ai_status, all_reasons)

    ModerationLog.objects.create(
        report=report,
        decision=ai_status,
        reasons=all_reasons,
        moderation_time=round(elapsed, 2),
    )

    return ai_status


def _moderate_text_onnx(text: str, reasons: list):
    encoding = _tokenizer.encode(text)
    input_ids = np.array([encoding.ids], dtype=np.int64)
    attention_mask = np.array([encoding.attention_mask], dtype=np.int64)

    logits = _text_session.run(None, {"input_ids": input_ids, "attention_mask": attention_mask})[0]
    pred_id = int(logits.argmax(axis=1)[0])
    pred_label = _labels.get(str(pred_id), "?")

    if pred_label != "NO":
        label_name = _LABEL_MAP.get(pred_label, pred_label)
        reasons.append(f"Text flagged as {label_name} (label {pred_id})")


def _moderate_text_multilingual(text: str, reasons: list):
    predictions = _hf_post_text("citizenlab/distilbert-base-multilingual-cased-toxicity", text)
    if not predictions:
        return
    for pred in predictions[0]:
        label = pred["label"].lower()
        score = pred["score"]
        if label == "toxic" and score > 0.5:
            reasons.append(f"Text flagged as toxic ({score:.2f})")


def _check_image_bytes(image_bytes: bytes, content_type: str, media_id: int, reasons: list):
    try:
        _check_metadata(image_bytes, media_id, reasons)
        if reasons:
            return
    except Exception:
        pass

    try:
        _check_nsfw(image_bytes, content_type, media_id, reasons)
        if reasons:
            return
    except Exception:
        pass

    try:
        _check_violence_local(image_bytes, media_id, reasons)
        if reasons:
            return
    except Exception:
        pass

    try:
        _check_deepfake_local(image_bytes, media_id, reasons)
    except Exception:
        pass


def _moderate_images(report: Report, reasons: list):
    images = list(report.images.all())
    if not images:
        return

    for img in images:
        try:
            url = img.image.build_url(secure=True)
            resp = requests.get(url, timeout=15)
            resp.raise_for_status()
            _check_image_bytes(resp.content, resp.headers.get("content-type", "image/jpeg"), img.id, reasons)
            if reasons:
                return
        except Exception:
            pass


def _moderate_videos(report: Report, reasons: list):
    videos = list(report.videos.all())
    if not videos:
        return

    for vid in videos:
        for ts in _VIDEO_TIMESTAMPS:
            try:
                frame = _extract_frame(vid.video.build_url(secure=True), ts)
                if not frame:
                    continue
                _check_image_bytes(frame, "image/png", vid.id, reasons)
                if reasons:
                    return
            except Exception:
                continue


def _check_metadata(image_bytes: bytes, media_id: int, reasons: list):
    try:
        img = PILImage.open(io.BytesIO(image_bytes))
        exif = img.getexif()
        if not exif or not dict(exif):
            return
        software = (exif.get(305, "") or "").lower()
        artist = (exif.get(315, "") or "").lower()
        copyright_note = (exif.get(33432, "") or "").lower()
        description = (exif.get(270, "") or "").lower()
        combined = f"{software} {artist} {copyright_note} {description}"
        for marker in _AI_EXIF_MARKERS:
            if marker in combined:
                reasons.append(f"Media {media_id} flagged by metadata: '{marker}' found")
                return
    except Exception:
        pass


def _check_nsfw(image_bytes: bytes, content_type: str, media_id: int, reasons: list):
    predictions = _hf_post(_NSFW_MODEL, image_bytes, content_type)
    for pred in predictions:
        label = pred["label"].lower()
        score = pred["score"]
        if label == "nsfw" and score > 0.5:
            reasons.append(f"Media {media_id} flagged as NSFW ({score:.2f})")


def _check_violence_local(image_bytes: bytes, media_id: int, reasons: list):
    img = PILImage.open(io.BytesIO(image_bytes)).convert("RGB")
    img = img.resize((224, 224))
    arr = np.array(img, dtype=np.float32) / 255.0
    arr = (arr - 0.5) / 0.5
    arr = arr.transpose(2, 0, 1)[np.newaxis, ...]

    logits = _violence_session.run(None, {"pixel_values": arr})[0]
    pred_id = int(logits.argmax(axis=1)[0])
    label = _violence_labels.get(str(pred_id), "?")
    if label == "LABEL_1":
        reasons.append(f"Media {media_id} flagged as violent")


def _check_deepfake_local(image_bytes: bytes, media_id: int, reasons: list):
    img = PILImage.open(io.BytesIO(image_bytes)).convert("RGB")
    img = img.resize((440, 440))
    left = (440 - 384) // 2
    img = img.crop((left, left, left + 384, left + 384))
    arr = np.array(img, dtype=np.float32) / 255.0
    mean = np.array(_deepfake_proc["image_mean"], dtype=np.float32)
    std = np.array(_deepfake_proc["image_std"], dtype=np.float32)
    arr = (arr - mean) / std
    arr = arr.transpose(2, 0, 1)[np.newaxis, ...]

    logits = _deepfake_session.run(None, {"pixel_values": arr})[0]
    pred_id = int(logits.argmax(axis=1)[0])
    label = _deepfake_labels.get(str(pred_id), "?")
    if label == "LABEL_1":
        reasons.append(f"Media {media_id} flagged as AI-generated")


def _apply_decision(report: Report, ai_status: str, reasons: list):
    if ai_status == Report.AIStatus.APPROVED:
        report.ai_status = Report.AIStatus.APPROVED
        report.visibility = True
        report.moderation_note = ""
    else:
        report.ai_status = Report.AIStatus.FLAGGED
        report.visibility = False
        report.moderation_note = "Flagged by AI: " + "; ".join(reasons)
    report.save(update_fields=["ai_status", "visibility", "moderation_note", "updated_at"])
