# Generated by Django 6.0.6 on 2026-07-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0005_report_moderation_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('flagged', 'Flagged')], max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('moderation_time', models.FloatField(help_text='Time taken in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
