# Generated by Django 6.0.6 on 2026-07-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
        ('reports', '0005_report_moderation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('UPVOTE', 'Upvote'), ('STATUS_UPDATE', 'Status Update'), ('PROGRESS_UPDATE', 'Progress Update'), ('NOTICE', 'Notice'), ('MODERATION', 'Moderation')], max_length=20),
        ),
    ]
